.class public final LX/Kf5;
.super Ljava/lang/Object;
.source ""

# interfaces
.implements LX/CaO;


# instance fields
.field public final $t:I

.field public final A00:Ljava/lang/Object;

.field public final A01:Ljava/lang/Object;


# direct methods
.method public constructor <init>(ILjava/lang/Object;Ljava/lang/Object;)V
    .locals 0

    iput p1, p0, LX/Kf5;->$t:I

    iput-object p3, p0, LX/Kf5;->A01:Ljava/lang/Object;

    iput-object p2, p0, LX/Kf5;->A00:Ljava/lang/Object;

    invoke-direct {p0}, Ljava/lang/Object;-><init>()V

    return-void
.end method


# virtual methods
.method public final Edg(Ljava/lang/Integer;)V
    .locals 5

    iget v0, p0, LX/Kf5;->$t:I

    iget-object v4, p0, LX/Kf5;->A01:Ljava/lang/Object;

    if-eqz v0, :cond_0

    check-cast v4, LX/5CX;

    iget-object v3, v4, LX/5CX;->A03:LX/67f;

    const/4 v2, 0x0

    iput-boolean v2, v3, LX/67f;->A11:Z

    iget-object v1, v4, LX/5CX;->A04:LX/LnX;

    iget-object v0, v4, LX/5CX;->A02:Lcom/instagram/model/reels/ReelItem;

    invoke-interface {v1, v0, v3, v2}, LX/LnX;->Fam(Lcom/instagram/model/reels/ReelItem;LX/67f;Z)V

    iget-object v1, v4, LX/5CX;->A00:LX/1tz;

    const v0, 0x81c177d

    invoke-virtual {v1, v0}, LX/9e6;->A0V(I)V

    return-void

    :cond_0
    check-cast v4, LX/5CO;

    iget-object v3, v4, LX/5CO;->A01:LX/67f;

    const/4 v2, 0x0

    iput-boolean v2, v3, LX/67f;->A11:Z

    iget-object v1, v4, LX/J4X;->A02:LX/LlC;

    const-string v0, "null cannot be cast to non-null type instagram.features.stories.viewer.sponsored.autogenerated.profileextension.ProfileExtensionCardActionHandler.Delegate"

    invoke-static {v1, v0}, LX/659;->A10(Ljava/lang/Object;Ljava/lang/String;)V

    check-cast v1, LX/LnW;

    iget-object v0, v4, LX/J4X;->A01:Lcom/instagram/model/reels/ReelItem;

    invoke-interface {v1, v0, v3, v2}, LX/LnW;->Fam(Lcom/instagram/model/reels/ReelItem;LX/67f;Z)V

    return-void
.end method

.method public final Eq8(LX/5cM;)V
    .locals 6

    iget v0, p0, LX/Kf5;->$t:I

    if-eqz v0, :cond_0

    const/4 v5, 0x0

    invoke-static {p1, v5}, LX/659;->A0y(Ljava/lang/Object;I)V

    iget-object v4, p0, LX/Kf5;->A01:Ljava/lang/Object;

    check-cast v4, LX/5CX;

    iget-object v3, v4, LX/5CX;->A03:LX/67f;

    const/4 v2, 0x1

    iput-boolean v2, v3, LX/67f;->A11:Z

    iget-object v1, p0, LX/Kf5;->A00:Ljava/lang/Object;

    check-cast v1, Landroid/view/View;

    const v0, 0x735fb603

    invoke-static {v1, v5, v0}, LX/08R;->A0S(Landroid/view/View;II)V

    iget-object v1, v4, LX/5CX;->A04:LX/LnX;

    iget-object v0, v4, LX/5CX;->A02:Lcom/instagram/model/reels/ReelItem;

    invoke-interface {v1, v0, v3, v2}, LX/LnX;->Fam(Lcom/instagram/model/reels/ReelItem;LX/67f;Z)V

    iget-object v3, v4, LX/5CX;->A00:LX/1tz;

    invoke-static {}, LX/011;->A0S()Ljava/lang/StringBuilder;

    move-result-object v2

    const-string v0, "Width - "

    invoke-static {v0, v2}, LX/Aug;->A0t(Ljava/lang/String;Ljava/lang/StringBuilder;)Ljava/lang/StringBuilder;

    iget-object v1, p1, LX/5cM;->A00:LX/5cL;

    iget v0, v1, LX/5cL;->A05:I

    invoke-virtual {v2, v0}, Ljava/lang/StringBuilder;->append(I)Ljava/lang/StringBuilder;

    const-string v0, "; height - "

    invoke-static {v0, v2}, LX/Aug;->A0t(Ljava/lang/String;Ljava/lang/StringBuilder;)Ljava/lang/StringBuilder;

    iget v0, v1, LX/5cL;->A02:I

    invoke-virtual {v2, v0}, Ljava/lang/StringBuilder;->append(I)Ljava/lang/StringBuilder;

    invoke-virtual {v2}, Ljava/lang/Object;->toString()Ljava/lang/String;

    move-result-object v1

    const v2, 0x81c177d

    const-string v0, "image_dimensions"

    invoke-virtual {v3, v2, v0, v1}, LX/9e6;->markerAnnotate(ILjava/lang/String;Ljava/lang/String;)V

    const-string v1, "image_load_source"

    iget-object v0, p1, LX/5cM;->A04:Ljava/lang/String;

    invoke-virtual {v3, v2, v1, v0}, LX/9e6;->markerAnnotate(ILjava/lang/String;Ljava/lang/String;)V

    invoke-virtual {v3, v2}, LX/9e6;->A0U(I)V

    return-void

    :cond_0
    invoke-static {p1}, LX/659;->A0u(Ljava/lang/Object;)V

    iget-object v4, p0, LX/Kf5;->A01:Ljava/lang/Object;

    check-cast v4, LX/5CO;

    iget-object v3, v4, LX/5CO;->A01:LX/67f;

    const/4 v2, 0x1

    iput-boolean v2, v3, LX/67f;->A11:Z

    iget-object v1, v4, LX/J4X;->A02:LX/LlC;

    const-string v0, "null cannot be cast to non-null type instagram.features.stories.viewer.sponsored.autogenerated.profileextension.ProfileExtensionCardActionHandler.Delegate"

    invoke-static {v1, v0}, LX/659;->A10(Ljava/lang/Object;Ljava/lang/String;)V

    check-cast v1, LX/LnW;

    iget-object v0, v4, LX/J4X;->A01:Lcom/instagram/model/reels/ReelItem;

    invoke-interface {v1, v0, v3, v2}, LX/LnW;->Fam(Lcom/instagram/model/reels/ReelItem;LX/67f;Z)V

    iget-object v0, p0, LX/Kf5;->A00:Ljava/lang/Object;

    check-cast v0, Lkotlin/jvm/functions/Function1;

    invoke-interface {v0, p1}, Lkotlin/jvm/functions/Function1;->invoke(Ljava/lang/Object;)Ljava/lang/Object;

    return-void
.end method
