.class public abstract LX/Unt;
.super Ljava/lang/Object;
.source ""


# annotations
.annotation build Lcom/facebook/ultralight/AutoGeneratedSwitchAppModuleSubClass;
    value = 0x1
.end annotation


# direct methods
.method public static A00(ILX/kiG;Ljava/lang/Object;)Ljava/lang/Object;
    .locals 1
    .annotation build Lcom/facebook/ultralight/AutoGeneratedSwitchSubClassMasterMethod;
    .end annotation

    .annotation build Ldalvik/annotation/optimization/NeverInline;
    .end annotation

    shr-int/lit8 v0, p0, 0x7

    and-int/lit8 v0, v0, 0xf

    if-nez v0, :cond_0

    invoke-static {p0, p1, p2}, LX/Unt;->A01(ILX/kiG;Ljava/lang/Object;)Ljava/lang/Object;

    move-result-object v0

    return-object v0

    :cond_0
    const-string v0, "Invalid Static DI binding id"

    invoke-static {v0}, LX/020;->A0e(Ljava/lang/String;)Ljava/lang/IllegalArgumentException;

    move-result-object v0

    throw v0
.end method

.method public static A01(ILX/kiG;Ljava/lang/Object;)Ljava/lang/Object;
    .locals 0

    shr-int/lit8 p0, p0, 0x0

    and-int/lit8 p0, p0, 0x7f

    packed-switch p0, :pswitch_data_0

    :pswitch_0
    const-string p0, "Invalid Static DI binding id"

    invoke-static {p0}, LX/020;->A0e(Ljava/lang/String;)Ljava/lang/IllegalArgumentException;

    move-result-object p0

    throw p0

    :pswitch_1
    invoke-static {p2}, LX/pA6;->A00(Ljava/lang/Object;)LX/p93;

    move-result-object p0

    return-object p0

    :pswitch_2
    invoke-static {}, LX/pAI;->A00()LX/p9v;

    move-result-object p0

    return-object p0

    :pswitch_3
    invoke-static {}, LX/pAI;->A02()LX/p9c;

    move-result-object p0

    return-object p0

    :pswitch_4
    invoke-static {}, LX/pAI;->A01()LX/p9b;

    move-result-object p0

    return-object p0

    :pswitch_5
    invoke-static {}, LX/pA7;->A00()LX/pA8;

    move-result-object p0

    return-object p0

    :pswitch_6
    invoke-static {}, LX/pA7;->A01()LX/p9e;

    move-result-object p0

    return-object p0

    :pswitch_7
    invoke-static {}, LX/p9Y;->A00()LX/p9Z;

    move-result-object p0

    return-object p0

    :pswitch_8
    invoke-static {}, LX/p9W;->A00()LX/p9X;

    move-result-object p0

    return-object p0

    :pswitch_9
    invoke-static {}, LX/pA6;->A01()LX/p9a;

    move-result-object p0

    return-object p0

    :pswitch_a
    invoke-static {}, LX/p9d;->A00()LX/pBL;

    move-result-object p0

    return-object p0

    :pswitch_b
    invoke-static {}, LX/p9j;->A00()LX/p9k;

    move-result-object p0

    return-object p0

    :pswitch_c
    invoke-static {}, LX/p9T;->A00()LX/p9V;

    move-result-object p0

    return-object p0

    :pswitch_data_0
    .packed-switch 0x0
        :pswitch_8
        :pswitch_9
        :pswitch_a
        :pswitch_b
        :pswitch_c
        :pswitch_1
        :pswitch_2
        :pswitch_3
        :pswitch_4
        :pswitch_5
        :pswitch_6
        :pswitch_0
        :pswitch_0
        :pswitch_7
        :pswitch_8
        :pswitch_9
        :pswitch_a
        :pswitch_b
        :pswitch_c
    .end packed-switch
.end method
