.class public final Lcom/instagram/creation/capture/quickcapture/sundial/edit/stacked/audio/beatmarkers/repository/ClipsAudioAutoGeneratedBeatsRepository;
.super LX/9lG;
.source ""


# instance fields
.field public A00:Ljava/lang/Long;

.field public final A01:Landroid/util/LruCache;

.field public final A02:LX/6fz;

.field public final A03:Lcom/instagram/common/session/UserSession;


# direct methods
.method public constructor <init>(Lcom/instagram/common/session/UserSession;)V
    .locals 2

    const v1, 0x4e13b44a    # 6.1951654E8f

    const/4 v0, 0x3

    invoke-static {v1, v0}, LX/7yr;->A01(II)LX/1zd;

    move-result-object v1

    const-string v0, "Reels"

    invoke-direct {p0, v0, v1}, LX/9lG;-><init>(Ljava/lang/String;LX/jAX;)V

    iput-object p1, p0, Lcom/instagram/creation/capture/quickcapture/sundial/edit/stacked/audio/beatmarkers/repository/ClipsAudioAutoGeneratedBeatsRepository;->A03:Lcom/instagram/common/session/UserSession;

    const/16 v1, 0xa

    new-instance v0, Landroid/util/LruCache;

    invoke-direct {v0, v1}, Landroid/util/LruCache;-><init>(I)V

    iput-object v0, p0, Lcom/instagram/creation/capture/quickcapture/sundial/edit/stacked/audio/beatmarkers/repository/ClipsAudioAutoGeneratedBeatsRepository;->A01:Landroid/util/LruCache;

    new-instance v0, LX/6fz;

    invoke-direct {v0}, LX/6fz;-><init>()V

    iput-object v0, p0, Lcom/instagram/creation/capture/quickcapture/sundial/edit/stacked/audio/beatmarkers/repository/ClipsAudioAutoGeneratedBeatsRepository;->A02:LX/6fz;

    return-void
.end method

.method public static final A00(Lcom/instagram/creation/capture/quickcapture/sundial/edit/stacked/audio/beatmarkers/repository/ClipsAudioAutoGeneratedBeatsRepository;Ljava/lang/String;LX/igO;LX/LEL;Lkotlin/jvm/functions/Function1;)Ljava/lang/Object;
    .locals 6

    const/4 v5, 0x1

    instance-of v0, p2, LX/KuU;

    if-eqz v0, :cond_0

    move-object v4, p2

    check-cast v4, LX/KuU;

    iget v0, v4, LX/KuU;->$t:I

    if-ne v0, v5, :cond_0

    iget v2, v4, LX/KuU;->A00:I

    const/high16 v1, -0x80000000

    and-int v0, v2, v1

    if-eqz v0, :cond_0

    sub-int/2addr v2, v1

    iput v2, v4, LX/KuU;->A00:I

    :goto_0
    iget-object v1, v4, LX/KuU;->A04:Ljava/lang/Object;

    sget-object v3, LX/2a1;->A02:LX/2a1;

    iget v2, v4, LX/KuU;->A00:I

    if-eqz v2, :cond_1

    if-eq v2, v5, :cond_2

    const-string v1, "call to \'resume\' before \'invoke\' with coroutine"

    new-instance v0, Ljava/lang/IllegalStateException;

    invoke-direct {v0, v1}, Ljava/lang/IllegalStateException;-><init>(Ljava/lang/String;)V

    throw v0

    :cond_0
    new-instance v4, LX/KuU;

    invoke-direct {v4, p0, p2, v5}, LX/KuU;-><init>(Lcom/instagram/creation/capture/quickcapture/sundial/edit/stacked/audio/beatmarkers/repository/ClipsAudioAutoGeneratedBeatsRepository;LX/igO;I)V

    goto :goto_0

    :cond_1
    invoke-static {v1}, LX/3mq;->A01(Ljava/lang/Object;)V

    iget-object v0, p0, Lcom/instagram/creation/capture/quickcapture/sundial/edit/stacked/audio/beatmarkers/repository/ClipsAudioAutoGeneratedBeatsRepository;->A03:Lcom/instagram/common/session/UserSession;

    invoke-static {v0, p1}, LX/Eyy;->A00(Lcom/instagram/common/session/UserSession;Ljava/lang/String;)LX/8kB;

    move-result-object v1

    iput-object p0, v4, LX/KuU;->A01:Ljava/lang/Object;

    iput-object p4, v4, LX/KuU;->A02:Ljava/lang/Object;

    iput-object p3, v4, LX/KuU;->A03:Ljava/lang/Object;

    iput v5, v4, LX/KuU;->A00:I

    const v0, 0x4e13b44a    # 6.1951654E8f

    invoke-virtual {v1, v0, v4}, LX/8kB;->A00(ILX/igO;)Ljava/lang/Object;

    move-result-object v1

    if-ne v1, v3, :cond_3

    return-object v3

    :cond_2
    iget-object p3, v4, LX/KuU;->A03:Ljava/lang/Object;

    check-cast p3, LX/LEL;

    iget-object p4, v4, LX/KuU;->A02:Ljava/lang/Object;

    check-cast p4, Lkotlin/jvm/functions/Function1;

    iget-object p0, v4, LX/KuU;->A01:Ljava/lang/Object;

    check-cast p0, Lcom/instagram/creation/capture/quickcapture/sundial/edit/stacked/audio/beatmarkers/repository/ClipsAudioAutoGeneratedBeatsRepository;

    invoke-static {v1}, LX/3mq;->A01(Ljava/lang/Object;)V

    :cond_3
    check-cast v1, LX/DmJ;

    instance-of v0, v1, LX/0QW;

    if-eqz v0, :cond_4

    check-cast v1, LX/0QW;

    iget-object v0, v1, LX/0QW;->A00:Ljava/lang/Object;

    check-cast v0, LX/AXT;

    iget-object v0, v0, LX/AXT;->A00:Ljava/util/List;

    invoke-static {v0}, LX/Atf;->A1I(Ljava/lang/Iterable;)Ljava/util/Set;

    move-result-object v0

    invoke-interface {p4, v0}, Lkotlin/jvm/functions/Function1;->invoke(Ljava/lang/Object;)Ljava/lang/Object;

    return-object v0

    :cond_4
    instance-of v0, v1, LX/4pI;

    if-eqz v0, :cond_6

    const-string v3, "ClipsAudioAutoGeneratedBeatsRepository"

    check-cast v1, LX/4pI;

    iget-object v2, v1, LX/4pI;->A00:Ljava/lang/Object;

    move-object v0, v2

    check-cast v0, LX/F8C;

    invoke-virtual {v0}, LX/F8C;->A01()Ljava/lang/Throwable;

    move-result-object v1

    const-string v0, "fetchAutoGeneratedBeats failed"

    invoke-static {v3, v0, v1}, LX/2kf;->A03(Ljava/lang/String;Ljava/lang/String;Ljava/lang/Throwable;)V

    iget-object v0, p0, Lcom/instagram/creation/capture/quickcapture/sundial/edit/stacked/audio/beatmarkers/repository/ClipsAudioAutoGeneratedBeatsRepository;->A00:Ljava/lang/Long;

    if-eqz v0, :cond_5

    invoke-virtual {v0}, Ljava/lang/Number;->longValue()J

    move-result-wide v4

    iget-object v0, p0, Lcom/instagram/creation/capture/quickcapture/sundial/edit/stacked/audio/beatmarkers/repository/ClipsAudioAutoGeneratedBeatsRepository;->A02:LX/6fz;

    invoke-virtual {v2}, Ljava/lang/Object;->toString()Ljava/lang/String;

    move-result-object v1

    const v3, 0x166639a7

    const-string v2, ""

    invoke-virtual/range {v0 .. v5}, LX/6fz;->A0B(Ljava/lang/String;Ljava/lang/String;IJ)J

    :cond_5
    const/4 v0, 0x0

    iput-object v0, p0, Lcom/instagram/creation/capture/quickcapture/sundial/edit/stacked/audio/beatmarkers/repository/ClipsAudioAutoGeneratedBeatsRepository;->A00:Ljava/lang/Long;

    invoke-interface {p3}, LX/LEL;->invoke()Ljava/lang/Object;

    return-object v0

    :cond_6
    new-instance v0, Lkotlin/NoWhenBranchMatchedException;

    invoke-direct {v0}, Ljava/lang/RuntimeException;-><init>()V

    throw v0
.end method


# virtual methods
.method public final A01(Ljava/lang/String;LX/igO;LX/LEL;Lkotlin/jvm/functions/Function1;)Ljava/lang/Object;
    .locals 19

    move-object/from16 v2, p1

    move-object/from16 v6, p3

    const/4 v4, 0x2

    move-object/from16 v5, p2

    instance-of v0, v5, LX/KuU;

    if-eqz v0, :cond_0

    move-object v0, v5

    check-cast v0, LX/KuU;

    iget v1, v0, LX/KuU;->$t:I

    const/4 v0, 0x1

    if-eq v1, v4, :cond_1

    :cond_0
    const/4 v0, 0x0

    :cond_1
    move-object/from16 v7, p0

    if-eqz v0, :cond_2

    move-object v8, v5

    check-cast v8, LX/KuU;

    iget v3, v8, LX/KuU;->A00:I

    const/high16 v1, -0x80000000

    and-int v0, v3, v1

    if-eqz v0, :cond_2

    sub-int/2addr v3, v1

    iput v3, v8, LX/KuU;->A00:I

    :goto_0
    iget-object v10, v8, LX/KuU;->A05:Ljava/lang/Object;

    sget-object v9, LX/2a1;->A02:LX/2a1;

    iget v1, v8, LX/KuU;->A00:I

    const/4 v5, 0x0

    const/4 v3, 0x1

    if-eqz v1, :cond_4

    if-eq v1, v3, :cond_3

    const-string v1, "call to \'resume\' before \'invoke\' with coroutine"

    new-instance v0, Ljava/lang/IllegalStateException;

    invoke-direct {v0, v1}, Ljava/lang/IllegalStateException;-><init>(Ljava/lang/String;)V

    throw v0

    :cond_2
    new-instance v8, LX/KuU;

    invoke-direct {v8, v7, v5, v4}, LX/KuU;-><init>(Lcom/instagram/creation/capture/quickcapture/sundial/edit/stacked/audio/beatmarkers/repository/ClipsAudioAutoGeneratedBeatsRepository;LX/igO;I)V

    goto :goto_0

    :cond_3
    move-object v12, v5

    iget-object v6, v8, LX/KuU;->A03:Ljava/lang/Object;

    check-cast v6, LX/LEL;

    iget-object v2, v8, LX/KuU;->A02:Ljava/lang/Object;

    iget-object v4, v8, LX/KuU;->A01:Ljava/lang/Object;

    check-cast v4, Lcom/instagram/creation/capture/quickcapture/sundial/edit/stacked/audio/beatmarkers/repository/ClipsAudioAutoGeneratedBeatsRepository;

    goto :goto_1

    :cond_4
    invoke-static {v10}, LX/3mq;->A01(Ljava/lang/Object;)V

    iget-object v4, v7, Lcom/instagram/creation/capture/quickcapture/sundial/edit/stacked/audio/beatmarkers/repository/ClipsAudioAutoGeneratedBeatsRepository;->A02:LX/6fz;

    const v10, 0x166639a7

    const-wide/16 v0, 0x1388

    invoke-virtual {v4, v10, v0, v1}, LX/6fz;->A06(IJ)J

    move-result-wide v0

    new-instance v11, Ljava/lang/Long;

    invoke-direct {v11, v0, v1}, Ljava/lang/Long;-><init>(J)V

    invoke-virtual {v11}, Ljava/lang/Number;->longValue()J

    move-result-wide v0

    const-string v10, "audio_id"

    invoke-virtual {v4, v0, v1, v10, v2}, LX/6fz;->A0G(JLjava/lang/String;Ljava/lang/String;)V

    iput-object v11, v7, Lcom/instagram/creation/capture/quickcapture/sundial/edit/stacked/audio/beatmarkers/repository/ClipsAudioAutoGeneratedBeatsRepository;->A00:Ljava/lang/Long;

    iget-object v1, v7, Lcom/instagram/creation/capture/quickcapture/sundial/edit/stacked/audio/beatmarkers/repository/ClipsAudioAutoGeneratedBeatsRepository;->A01:Landroid/util/LruCache;

    const v0, 0xe8b6191

    invoke-static {v1, v2, v0}, LX/BRU;->A00(Landroid/util/LruCache;Ljava/lang/Object;I)Ljava/lang/Object;

    move-result-object v12

    if-nez v12, :cond_8

    :try_start_0
    iget-object v0, v7, Lcom/instagram/creation/capture/quickcapture/sundial/edit/stacked/audio/beatmarkers/repository/ClipsAudioAutoGeneratedBeatsRepository;->A00:Ljava/lang/Long;

    if-eqz v0, :cond_5

    invoke-virtual {v0}, Ljava/lang/Number;->longValue()J

    move-result-wide v0

    const-string v11, "cached"

    const-string v10, "false"

    invoke-virtual {v4, v0, v1, v11, v10}, LX/6fz;->A0G(JLjava/lang/String;Ljava/lang/String;)V

    const-string v10, "server_fetch_start"

    invoke-virtual {v4, v0, v1, v10}, LX/6fz;->A0D(JLjava/lang/String;)V

    :cond_5
    iput-object v7, v8, LX/KuU;->A01:Ljava/lang/Object;

    iput-object v2, v8, LX/KuU;->A02:Ljava/lang/Object;

    iput-object v6, v8, LX/KuU;->A03:Ljava/lang/Object;

    iput v3, v8, LX/KuU;->A00:I

    move-object/from16 v0, p4

    invoke-static {v7, v2, v8, v6, v0}, Lcom/instagram/creation/capture/quickcapture/sundial/edit/stacked/audio/beatmarkers/repository/ClipsAudioAutoGeneratedBeatsRepository;->A00(Lcom/instagram/creation/capture/quickcapture/sundial/edit/stacked/audio/beatmarkers/repository/ClipsAudioAutoGeneratedBeatsRepository;Ljava/lang/String;LX/igO;LX/LEL;Lkotlin/jvm/functions/Function1;)Ljava/lang/Object;

    move-result-object v10

    if-ne v10, v9, :cond_6

    return-object v9

    :cond_6
    move-object v4, v7

    goto :goto_2
    :try_end_0
    .catch Ljava/io/IOException; {:try_start_0 .. :try_end_0} :catch_1

    :goto_1
    :try_start_1
    invoke-static {v10}, LX/3mq;->A01(Ljava/lang/Object;)V

    :goto_2
    check-cast v10, Ljava/util/Set;

    if-eqz v10, :cond_7
    :try_end_1
    .catch Ljava/io/IOException; {:try_start_1 .. :try_end_1} :catch_0

    :try_start_2
    invoke-interface {v10}, Ljava/util/Set;->isEmpty()Z

    move-result v0

    if-nez v0, :cond_7

    iget-object v0, v4, Lcom/instagram/creation/capture/quickcapture/sundial/edit/stacked/audio/beatmarkers/repository/ClipsAudioAutoGeneratedBeatsRepository;->A01:Landroid/util/LruCache;

    invoke-virtual {v0, v2, v10}, Landroid/util/LruCache;->put(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;

    :cond_7
    move-object v12, v10

    goto :goto_3
    :try_end_2
    .catch Ljava/io/IOException; {:try_start_2 .. :try_end_2} :catch_2

    :cond_8
    :try_start_3
    iget-object v0, v7, Lcom/instagram/creation/capture/quickcapture/sundial/edit/stacked/audio/beatmarkers/repository/ClipsAudioAutoGeneratedBeatsRepository;->A00:Ljava/lang/Long;

    if-eqz v0, :cond_9

    invoke-virtual {v0}, Ljava/lang/Number;->longValue()J

    move-result-wide v2

    const-string v1, "cached"

    const-string v0, "true"

    invoke-virtual {v4, v2, v3, v1, v0}, LX/6fz;->A0G(JLjava/lang/String;Ljava/lang/String;)V

    :cond_9
    move-object v4, v7
    :try_end_3
    .catch Ljava/io/IOException; {:try_start_3 .. :try_end_3} :catch_1

    :goto_3
    :try_start_4
    iget-object v0, v4, Lcom/instagram/creation/capture/quickcapture/sundial/edit/stacked/audio/beatmarkers/repository/ClipsAudioAutoGeneratedBeatsRepository;->A00:Ljava/lang/Long;

    if-eqz v0, :cond_a

    invoke-virtual {v0}, Ljava/lang/Number;->longValue()J

    move-result-wide v2

    iget-object v7, v4, Lcom/instagram/creation/capture/quickcapture/sundial/edit/stacked/audio/beatmarkers/repository/ClipsAudioAutoGeneratedBeatsRepository;->A02:LX/6fz;

    const v1, 0x166639a7

    const-string v0, ""

    invoke-virtual {v7, v2, v3, v1, v0}, LX/6fz;->A07(JILjava/lang/String;)J

    :cond_a
    iput-object v5, v4, Lcom/instagram/creation/capture/quickcapture/sundial/edit/stacked/audio/beatmarkers/repository/ClipsAudioAutoGeneratedBeatsRepository;->A00:Ljava/lang/Long;

    return-object v12
    :try_end_4
    .catch Ljava/io/IOException; {:try_start_4 .. :try_end_4} :catch_0

    :catch_0
    move-exception v2

    goto :goto_4

    :catch_1
    move-exception v2

    move-object v4, v7

    goto :goto_4

    :catch_2
    move-exception v2

    move-object v12, v10

    :goto_4
    const-string v1, "ClipsAudioAutoGeneratedBeatsRepository"

    const-string v0, "getAutoGeneratedBeats failed"

    invoke-static {v1, v0, v2}, LX/2kf;->A03(Ljava/lang/String;Ljava/lang/String;Ljava/lang/Throwable;)V

    iget-object v0, v4, Lcom/instagram/creation/capture/quickcapture/sundial/edit/stacked/audio/beatmarkers/repository/ClipsAudioAutoGeneratedBeatsRepository;->A00:Ljava/lang/Long;

    if-eqz v0, :cond_b

    invoke-virtual {v0}, Ljava/lang/Number;->longValue()J

    move-result-wide v17

    iget-object v13, v4, Lcom/instagram/creation/capture/quickcapture/sundial/edit/stacked/audio/beatmarkers/repository/ClipsAudioAutoGeneratedBeatsRepository;->A02:LX/6fz;

    invoke-virtual {v2}, Ljava/lang/Object;->toString()Ljava/lang/String;

    move-result-object v14

    const v16, 0x166639a7

    const-string v15, ""

    invoke-virtual/range {v13 .. v18}, LX/6fz;->A0B(Ljava/lang/String;Ljava/lang/String;IJ)J

    :cond_b
    iput-object v5, v4, Lcom/instagram/creation/capture/quickcapture/sundial/edit/stacked/audio/beatmarkers/repository/ClipsAudioAutoGeneratedBeatsRepository;->A00:Ljava/lang/Long;

    invoke-interface {v6}, LX/LEL;->invoke()Ljava/lang/Object;

    return-object v12
.end method
