.class public Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;
.super Ljava/lang/Object;
.source ""

# interfaces
.implements Ljava/io/Serializable;


# static fields
.field public static final A3Z:Lcom/facebook/video/heroplayer/setting/FbAutogeneratedSettings;

.field public static final A3a:Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;


# instance fields
.field public A00:J

.field public A01:LX/6aV;

.field public A02:Z

.field public final A03:D

.field public final A04:I

.field public final A05:I

.field public final A06:I

.field public final A07:I

.field public final A08:I

.field public final A09:I

.field public final A0A:I

.field public final A0B:I

.field public final A0C:I

.field public final A0D:I

.field public final A0E:I

.field public final A0F:I

.field public final A0G:I

.field public final A0H:I

.field public final A0I:I

.field public final A0J:I

.field public final A0K:I

.field public final A0L:I

.field public final A0M:I

.field public final A0N:I

.field public final A0O:I

.field public final A0P:I

.field public final A0Q:I

.field public final A0R:I

.field public final A0S:I

.field public final A0T:I

.field public final A0U:I

.field public final A0V:I

.field public final A0W:I

.field public final A0X:I

.field public final A0Y:I

.field public final A0Z:I

.field public final A0a:I

.field public final A0b:I

.field public final A0c:I

.field public final A0d:I

.field public final A0e:I

.field public final A0f:J

.field public final A0g:J

.field public final A0h:LX/6br;

.field public final A0i:LX/6br;

.field public final A0j:LX/6br;

.field public final A0k:LX/6br;

.field public final A0l:LX/6br;

.field public final A0m:LX/6br;

.field public final A0n:LX/6br;

.field public final A0o:LX/6br;

.field public final A0p:LX/6br;

.field public final A0q:LX/6bv;

.field public final A0r:LX/6bn;

.field public final A0s:LX/6bl;

.field public final A0t:LX/6bk;

.field public final A0u:LX/6bj;

.field public final A0v:LX/6bp;

.field public final A0w:LX/6aX;

.field public final A0x:Lcom/facebook/video/heroplayer/setting/FbAutogeneratedSettings;

.field public final A0y:LX/6bw;

.field public final A0z:LX/6bi;

.field public final A10:LX/6bt;

.field public final A11:LX/6gc;

.field public final A12:LX/6bg;

.field public final A13:LX/6bg;

.field public final A14:LX/6bq;

.field public final A15:Ljava/lang/String;

.field public final A16:Ljava/lang/String;

.field public final A17:Ljava/lang/String;

.field public final A18:Ljava/util/HashSet;

.field public final A19:Ljava/util/Map;

.field public final A1A:Ljava/util/Set;

.field public final A1B:Ljava/util/Set;

.field public final A1C:Ljava/util/Set;

.field public final A1D:Ljava/util/Set;

.field public final A1E:Ljava/util/Set;

.field public final A1F:Ljava/util/Set;

.field public final A1G:Ljava/util/Set;

.field public final A1H:Ljava/util/Set;

.field public final A1I:Z

.field public final A1J:Z

.field public final A1K:Z

.field public final A1L:Z

.field public final A1M:Z

.field public final A1N:Z

.field public final A1O:Z

.field public final A1P:Z

.field public final A1Q:Z

.field public final A1R:Z

.field public final A1S:Z

.field public final A1T:Z

.field public final A1U:Z

.field public final A1V:Z

.field public final A1W:Z

.field public final A1X:Z

.field public final A1Y:Z

.field public final A1Z:Z

.field public final A1a:Z

.field public final A1b:Z

.field public final A1c:Z

.field public final A1d:Z

.field public final A1e:Z

.field public final A1f:Z

.field public final A1g:Z

.field public final A1h:Z

.field public final A1i:Z

.field public final A1j:Z

.field public final A1k:Z

.field public final A1l:Z

.field public final A1m:Z

.field public final A1n:Z

.field public final A1o:Z

.field public final A1p:Z

.field public final A1q:Z

.field public final A1r:Z

.field public final A1s:Z

.field public final A1t:Z

.field public final A1u:Z

.field public final A1v:Z

.field public final A1w:Z

.field public final A1x:Z

.field public final A1y:Z

.field public final A1z:Z

.field public final A20:Z

.field public final A21:Z

.field public final A22:Z

.field public final A23:Z

.field public final A24:Z

.field public final A25:Z

.field public final A26:Z

.field public final A27:Z

.field public final A28:Z

.field public final A29:Z

.field public final A2A:Z

.field public final A2B:Z

.field public final A2C:Z

.field public final A2D:Z

.field public final A2E:Z

.field public final A2F:Z

.field public final A2G:Z

.field public final A2H:Z

.field public final A2I:Z

.field public final A2J:Z

.field public final A2K:Z

.field public final A2L:Z

.field public final A2M:Z

.field public final A2N:Z

.field public final A2O:Z

.field public final A2P:Z

.field public final A2Q:Z

.field public final A2R:Z

.field public final A2S:Z

.field public final A2T:Z

.field public final A2U:Z

.field public final A2V:Z

.field public final A2W:Z

.field public final A2X:Z

.field public final A2Y:Z

.field public final A2Z:Z

.field public final A2a:Z

.field public final A2b:Z

.field public final A2c:Z

.field public final A2d:Z

.field public final A2e:Z

.field public final A2f:Z

.field public final A2g:Z

.field public final A2h:Z

.field public final A2i:Z

.field public final A2j:Z

.field public final A2k:Z

.field public final A2l:Z

.field public final A2m:Z

.field public final A2n:Z

.field public final A2o:Z

.field public final A2p:Z

.field public final A2q:Z

.field public final A2r:Z

.field public final A2s:Z

.field public final A2t:Z

.field public final A2u:Z

.field public final A2v:Z

.field public final A2w:Z

.field public final A2x:Z

.field public final A2y:Z

.field public final A2z:Z

.field public final A30:Z

.field public final A31:Z

.field public final A32:Z

.field public final A33:Z

.field public final A34:Z

.field public final A35:Z

.field public final A36:Z

.field public final A37:Z

.field public final A38:Z

.field public final A39:Z

.field public final A3A:Z

.field public final A3B:Z

.field public final A3C:Z

.field public final A3D:Z

.field public final A3E:Z

.field public final A3F:Z

.field public final A3G:Z

.field public final A3H:Z

.field public final A3I:Z

.field public final A3J:Z

.field public final A3K:Z

.field public final A3L:Z

.field public final A3M:Z

.field public final A3N:Z

.field public final A3O:Z

.field public final A3P:Z

.field public final A3Q:Z

.field public final A3R:Z

.field public final A3S:Z

.field public final A3T:Z

.field public final A3U:Z

.field public final A3V:Z

.field public final A3W:Z

.field public final A3X:Z

.field public final A3Y:Z


# direct methods
.method public static constructor <clinit>()V
    .locals 2

    .line 0
    new-instance v0, Lcom/facebook/video/heroplayer/setting/FbAutogeneratedSettings;

    .line 2
    invoke-direct {v0}, Lcom/facebook/video/heroplayer/setting/FbAutogeneratedSettings;-><init>()V

    .line 5
    sput-object v0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A3Z:Lcom/facebook/video/heroplayer/setting/FbAutogeneratedSettings;

    .line 7
    new-instance v1, LX/6aU;

    .line 9
    invoke-direct {v1}, LX/6aU;-><init>()V

    .line 12
    new-instance v0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;

    .line 14
    invoke-direct {v0, v1}, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;-><init>(LX/6aU;)V

    .line 17
    sput-object v0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A3a:Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;

    .line 19
    return-void
.end method

.method public constructor <init>(LX/6aU;)V
    .locals 256

    .line 0
    move-object/from16 v1, p0

    .line 2
    invoke-direct {v1}, Ljava/lang/Object;-><init>()V

    .line 5
    move-object/from16 v2, p1

    .line 7
    iget-boolean v0, v2, LX/6aU;->A1k:Z

    .line 9
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1k:Z

    .line 11
    iget-object v0, v2, LX/6aU;->A0x:Lcom/facebook/video/heroplayer/setting/FbAutogeneratedSettings;

    .line 13
    iput-object v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0x:Lcom/facebook/video/heroplayer/setting/FbAutogeneratedSettings;

    .line 15
    iget-boolean v0, v2, LX/6aU;->A2k:Z

    .line 17
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2g:Z

    .line 19
    iget v0, v2, LX/6aU;->A0V:I

    .line 21
    iput v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0X:I

    .line 23
    iget-boolean v0, v2, LX/6aU;->A3G:Z

    .line 25
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A3E:Z

    .line 27
    iget-object v0, v2, LX/6aU;->A17:Ljava/lang/String;

    .line 29
    iput-object v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A17:Ljava/lang/String;

    .line 31
    iget-boolean v0, v2, LX/6aU;->A2K:Z

    .line 33
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2J:Z

    .line 35
    iget-boolean v0, v2, LX/6aU;->A27:Z

    .line 37
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A25:Z

    .line 39
    iget-boolean v0, v2, LX/6aU;->A3S:Z

    .line 41
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A3Q:Z

    .line 43
    iget-boolean v0, v2, LX/6aU;->A2l:Z

    .line 45
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2h:Z

    .line 47
    iget-object v0, v2, LX/6aU;->A0v:LX/6aX;

    .line 49
    iput-object v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0w:LX/6aX;

    .line 51
    iget-boolean v0, v2, LX/6aU;->A2M:Z

    .line 53
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2L:Z

    .line 55
    iget-object v0, v2, LX/6aU;->A12:LX/6bg;

    .line 57
    iput-object v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A12:LX/6bg;

    .line 59
    iget-object v0, v2, LX/6aU;->A13:LX/6bg;

    .line 61
    iput-object v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A13:LX/6bg;

    .line 63
    iget-boolean v0, v2, LX/6aU;->A1S:Z

    .line 65
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1R:Z

    .line 67
    iget-object v0, v2, LX/6aU;->A0z:LX/6bi;

    .line 69
    iput-object v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0z:LX/6bi;

    .line 71
    iget-boolean v0, v2, LX/6aU;->A32:Z

    .line 73
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A30:Z

    .line 75
    iget-boolean v0, v2, LX/6aU;->A36:Z

    .line 77
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A34:Z

    .line 79
    iget-object v0, v2, LX/6aU;->A0t:LX/6bj;

    .line 81
    iput-object v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0u:LX/6bj;

    .line 83
    iget-object v0, v2, LX/6aU;->A0s:LX/6bk;

    .line 85
    iput-object v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0t:LX/6bk;

    .line 87
    iget-object v0, v2, LX/6aU;->A0r:LX/6bl;

    .line 89
    iput-object v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0s:LX/6bl;

    .line 91
    iget-object v0, v2, LX/6aU;->A0q:LX/6bn;

    .line 93
    iput-object v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0r:LX/6bn;

    .line 95
    iget-object v0, v2, LX/6aU;->A11:LX/6gc;

    .line 97
    iput-object v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A11:LX/6gc;

    .line 99
    iget-object v0, v2, LX/6aU;->A0u:LX/6bp;

    .line 101
    iput-object v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0v:LX/6bp;

    .line 103
    iget-boolean v0, v2, LX/6aU;->A29:Z

    .line 105
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A27:Z

    .line 107
    iget-object v0, v2, LX/6aU;->A14:LX/6bq;

    .line 109
    iput-object v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A14:LX/6bq;

    .line 111
    iget v0, v2, LX/6aU;->A07:I

    .line 113
    iput v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0A:I

    .line 115
    iget v0, v2, LX/6aU;->A06:I

    .line 117
    iput v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A09:I

    .line 119
    iget-object v0, v2, LX/6aU;->A0h:LX/6br;

    .line 121
    iput-object v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0i:LX/6br;

    .line 123
    iget-object v0, v2, LX/6aU;->A0i:LX/6br;

    .line 125
    iput-object v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0j:LX/6br;

    .line 127
    iget-object v0, v2, LX/6aU;->A0k:LX/6br;

    .line 129
    iput-object v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0l:LX/6br;

    .line 131
    iget-object v0, v2, LX/6aU;->A0l:LX/6br;

    .line 133
    iput-object v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0m:LX/6br;

    .line 135
    iget-boolean v0, v2, LX/6aU;->A26:Z

    .line 137
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A24:Z

    .line 139
    iget-object v0, v2, LX/6aU;->A0j:LX/6br;

    .line 141
    iput-object v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0k:LX/6br;

    .line 143
    iget-object v0, v2, LX/6aU;->A0n:LX/6br;

    .line 145
    iput-object v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0o:LX/6br;

    .line 147
    iget-boolean v0, v2, LX/6aU;->A2a:Z

    .line 149
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2Y:Z

    .line 151
    iget v0, v2, LX/6aU;->A0W:I

    .line 153
    iput v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0Y:I

    .line 155
    iget-boolean v0, v2, LX/6aU;->A1M:Z

    .line 157
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1L:Z

    .line 159
    iget-boolean v0, v2, LX/6aU;->A3J:Z

    .line 161
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A3H:Z

    .line 163
    iget-boolean v0, v2, LX/6aU;->A2h:Z

    .line 165
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2d:Z

    .line 167
    iget-wide v3, v2, LX/6aU;->A0f:J

    .line 169
    iput-wide v3, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0g:J

    .line 171
    iget-boolean v0, v2, LX/6aU;->A3F:Z

    .line 173
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A3D:Z

    .line 175
    iget-boolean v0, v2, LX/6aU;->A1U:Z

    .line 177
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1T:Z

    .line 179
    iget-object v0, v2, LX/6aU;->A16:Ljava/lang/String;

    .line 181
    iput-object v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A16:Ljava/lang/String;

    .line 183
    iget-boolean v0, v2, LX/6aU;->A1w:Z

    .line 185
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1w:Z

    .line 187
    iget-boolean v0, v2, LX/6aU;->A39:Z

    .line 189
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A37:Z

    .line 191
    iget-boolean v0, v2, LX/6aU;->A1d:Z

    .line 193
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1c:Z

    .line 195
    iget-boolean v0, v2, LX/6aU;->A1l:Z

    .line 197
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1l:Z

    .line 199
    iget-boolean v0, v2, LX/6aU;->A2r:Z

    .line 201
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2p:Z

    .line 203
    iget-boolean v0, v2, LX/6aU;->A2z:Z

    .line 205
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2x:Z

    .line 207
    iget-boolean v0, v2, LX/6aU;->A2g:Z

    .line 209
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2c:Z

    .line 211
    iget-boolean v0, v2, LX/6aU;->A1J:Z

    .line 213
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1I:Z

    .line 215
    iget-boolean v0, v2, LX/6aU;->A3W:Z

    .line 217
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A3U:Z

    .line 219
    iget-boolean v0, v2, LX/6aU;->A2E:Z

    .line 221
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2C:Z

    .line 223
    iget-boolean v0, v2, LX/6aU;->A2D:Z

    .line 225
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2B:Z

    .line 227
    iget v0, v2, LX/6aU;->A0L:I

    .line 229
    iput v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0N:I

    .line 231
    iget-boolean v0, v2, LX/6aU;->A2m:Z

    .line 233
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2i:Z

    .line 235
    iget-boolean v0, v2, LX/6aU;->A2n:Z

    .line 237
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2j:Z

    .line 239
    iget-boolean v0, v2, LX/6aU;->A3R:Z

    .line 241
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A3P:Z

    .line 243
    iget-boolean v0, v2, LX/6aU;->A2f:Z

    .line 245
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2m:Z

    .line 247
    iget-boolean v0, v2, LX/6aU;->A2e:Z

    .line 249
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2k:Z

    .line 251
    iget-boolean v0, v2, LX/6aU;->A2t:Z

    .line 253
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2q:Z

    .line 255
    iget-boolean v0, v2, LX/6aU;->A3a:Z

    .line 257
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A3Y:Z

    .line 259
    iget-boolean v0, v2, LX/6aU;->A3Z:Z

    .line 261
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A3X:Z

    .line 263
    iget-boolean v0, v2, LX/6aU;->A2x:Z

    .line 265
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2v:Z

    .line 267
    iget-boolean v0, v2, LX/6aU;->A2p:Z

    .line 269
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2n:Z

    .line 271
    iget-boolean v0, v2, LX/6aU;->A3D:Z

    .line 273
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A3B:Z

    .line 275
    iget-boolean v0, v2, LX/6aU;->A2S:Z

    .line 277
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2R:Z

    .line 279
    iget-boolean v0, v2, LX/6aU;->A2Y:Z

    .line 281
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2W:Z

    .line 283
    iget-boolean v0, v2, LX/6aU;->A2P:Z

    .line 285
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2O:Z

    .line 287
    iget-boolean v0, v2, LX/6aU;->A35:Z

    .line 289
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A33:Z

    .line 291
    iget-boolean v0, v2, LX/6aU;->A3X:Z

    .line 293
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A3V:Z

    .line 295
    iget-boolean v0, v2, LX/6aU;->A3Q:Z

    .line 297
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A3O:Z

    .line 299
    iget-boolean v0, v2, LX/6aU;->A3M:Z

    .line 301
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A3K:Z

    .line 303
    iget v0, v2, LX/6aU;->A0F:I

    .line 305
    iput v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0H:I

    .line 307
    iget-boolean v0, v2, LX/6aU;->A3I:Z

    .line 309
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A3G:Z

    .line 311
    iget-boolean v0, v2, LX/6aU;->A2o:Z

    .line 313
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2l:Z

    .line 315
    iget-boolean v0, v2, LX/6aU;->A3H:Z

    .line 317
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A3F:Z

    .line 319
    iget v0, v2, LX/6aU;->A0Z:I

    .line 321
    iput v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0b:I

    .line 323
    iget-boolean v0, v2, LX/6aU;->A3U:Z

    .line 325
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A3S:Z

    .line 327
    iget-boolean v0, v2, LX/6aU;->A3T:Z

    .line 329
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A3R:Z

    .line 331
    iget-boolean v0, v2, LX/6aU;->A2H:Z

    .line 333
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2F:Z

    .line 335
    iget-boolean v0, v2, LX/6aU;->A3N:Z

    .line 337
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A3L:Z

    .line 339
    iget v0, v2, LX/6aU;->A0Q:I

    .line 341
    iput v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0S:I

    .line 343
    iget-boolean v0, v2, LX/6aU;->A1V:Z

    .line 345
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1U:Z

    .line 347
    iget-boolean v0, v2, LX/6aU;->A2s:Z

    .line 349
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2r:Z

    .line 351
    iget v0, v2, LX/6aU;->A0R:I

    .line 353
    iput v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0T:I

    .line 355
    iget v0, v2, LX/6aU;->A0G:I

    .line 357
    iput v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0I:I

    .line 359
    iget v0, v2, LX/6aU;->A0H:I

    .line 361
    iput v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0J:I

    .line 363
    iget-boolean v0, v2, LX/6aU;->A2y:Z

    .line 365
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2w:Z

    .line 367
    iget-boolean v0, v2, LX/6aU;->A1m:Z

    .line 369
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1m:Z

    .line 371
    iget-object v0, v2, LX/6aU;->A15:Ljava/lang/String;

    .line 373
    iput-object v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A15:Ljava/lang/String;

    .line 375
    iget-boolean v0, v2, LX/6aU;->A2c:Z

    .line 377
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2a:Z

    .line 379
    iget v0, v2, LX/6aU;->A0K:I

    .line 381
    iput v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0M:I

    .line 383
    iget v0, v2, LX/6aU;->A0J:I

    .line 385
    iput v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0L:I

    .line 387
    iget-boolean v0, v2, LX/6aU;->A1Q:Z

    .line 389
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1P:Z

    .line 391
    iget-boolean v0, v2, LX/6aU;->A30:Z

    .line 393
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2y:Z

    .line 395
    iget-boolean v0, v2, LX/6aU;->A31:Z

    .line 397
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2z:Z

    .line 399
    iget-object v0, v2, LX/6aU;->A18:Ljava/util/HashSet;

    .line 401
    iput-object v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A18:Ljava/util/HashSet;

    .line 403
    iget-boolean v0, v2, LX/6aU;->A1K:Z

    .line 405
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1J:Z

    .line 407
    iget v0, v2, LX/6aU;->A0B:I

    .line 409
    iput v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0E:I

    .line 411
    iget v0, v2, LX/6aU;->A09:I

    .line 413
    iput v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0C:I

    .line 415
    iget v0, v2, LX/6aU;->A0A:I

    .line 417
    iput v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0D:I

    .line 419
    iget-boolean v0, v2, LX/6aU;->A2R:Z

    .line 421
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2Q:Z

    .line 423
    iget-boolean v0, v2, LX/6aU;->A1Z:Z

    .line 425
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1Y:Z

    .line 427
    iget v0, v2, LX/6aU;->A0S:I

    .line 429
    iput v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0U:I

    .line 431
    iget v0, v2, LX/6aU;->A0T:I

    .line 433
    iput v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0V:I

    .line 435
    iget v0, v2, LX/6aU;->A0U:I

    .line 437
    iput v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0W:I

    .line 439
    iget-boolean v0, v2, LX/6aU;->A2A:Z

    .line 441
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A28:Z

    .line 443
    iget-boolean v0, v2, LX/6aU;->A1h:Z

    .line 445
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1h:Z

    .line 447
    iget-boolean v0, v2, LX/6aU;->A34:Z

    .line 449
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A32:Z

    .line 451
    iget-boolean v0, v2, LX/6aU;->A1g:Z

    .line 453
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1g:Z

    .line 455
    iget-boolean v0, v2, LX/6aU;->A1f:Z

    .line 457
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1f:Z

    .line 459
    iget-boolean v0, v2, LX/6aU;->A3C:Z

    .line 461
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A3A:Z

    .line 463
    iget-boolean v0, v2, LX/6aU;->A1L:Z

    .line 465
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1K:Z

    .line 467
    iget v0, v2, LX/6aU;->A0P:I

    .line 469
    iput v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0R:I

    .line 471
    iget-boolean v0, v2, LX/6aU;->A1O:Z

    .line 473
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1N:Z

    .line 475
    iget-wide v3, v2, LX/6aU;->A0d:J

    .line 477
    iput-wide v3, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0f:J

    .line 479
    iget-boolean v0, v2, LX/6aU;->A33:Z

    .line 481
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A31:Z

    .line 483
    iget-boolean v0, v2, LX/6aU;->A3O:Z

    .line 485
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A3M:Z

    .line 487
    iget v0, v2, LX/6aU;->A0b:I

    .line 489
    iput v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0d:I

    .line 491
    iget v0, v2, LX/6aU;->A02:I

    .line 493
    iput v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A05:I

    .line 495
    iget-boolean v0, v2, LX/6aU;->A2F:Z

    .line 497
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2D:Z

    .line 499
    iget-boolean v0, v2, LX/6aU;->A2G:Z

    .line 501
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2E:Z

    .line 503
    iget-wide v3, v2, LX/6aU;->A00:D

    .line 505
    iput-wide v3, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A03:D

    .line 507
    iget-boolean v0, v2, LX/6aU;->A3K:Z

    .line 509
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A3I:Z

    .line 511
    iget-boolean v0, v2, LX/6aU;->A2w:Z

    .line 513
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2u:Z

    .line 515
    iget v0, v2, LX/6aU;->A0N:I

    .line 517
    iput v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0P:I

    .line 519
    iget v0, v2, LX/6aU;->A0X:I

    .line 521
    iput v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0Z:I

    .line 523
    iget v0, v2, LX/6aU;->A0Y:I

    .line 525
    iput v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0a:I

    .line 527
    iget-boolean v0, v2, LX/6aU;->A2V:Z

    .line 529
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2U:Z

    .line 531
    iget-boolean v0, v2, LX/6aU;->A2U:Z

    .line 533
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2T:Z

    .line 535
    iget-boolean v0, v2, LX/6aU;->A2T:Z

    .line 537
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2S:Z

    .line 539
    iget v0, v2, LX/6aU;->A0M:I

    .line 541
    iput v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0O:I

    .line 543
    iget-object v0, v2, LX/6aU;->A1A:Ljava/util/Set;

    .line 545
    iput-object v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1A:Ljava/util/Set;

    .line 547
    iget-boolean v0, v2, LX/6aU;->A2C:Z

    .line 549
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2A:Z

    .line 551
    iget-boolean v0, v2, LX/6aU;->A2J:Z

    .line 553
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2I:Z

    .line 555
    iget-boolean v0, v2, LX/6aU;->A24:Z

    .line 557
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A22:Z

    .line 559
    iget-boolean v0, v2, LX/6aU;->A2i:Z

    .line 561
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2e:Z

    .line 563
    iget-boolean v0, v2, LX/6aU;->A1q:Z

    .line 565
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1q:Z

    .line 567
    iget-boolean v0, v2, LX/6aU;->A2Q:Z

    .line 569
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2P:Z

    .line 571
    iget-boolean v0, v2, LX/6aU;->A1R:Z

    .line 573
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1Q:Z

    .line 575
    iget-boolean v0, v2, LX/6aU;->A2B:Z

    .line 577
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A29:Z

    .line 579
    iget v0, v2, LX/6aU;->A0c:I

    .line 581
    iput v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0e:I

    .line 583
    iget-boolean v0, v2, LX/6aU;->A3Y:Z

    .line 585
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A3W:Z

    .line 587
    iget-boolean v0, v2, LX/6aU;->A3L:Z

    .line 589
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A3J:Z

    .line 591
    iget-object v0, v2, LX/6aU;->A0o:LX/6br;

    .line 593
    iput-object v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0p:LX/6br;

    .line 595
    iget-object v0, v2, LX/6aU;->A0g:LX/6br;

    .line 597
    iput-object v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0h:LX/6br;

    .line 599
    iget-object v0, v2, LX/6aU;->A0m:LX/6br;

    .line 601
    iput-object v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0n:LX/6br;

    .line 603
    iget-boolean v0, v2, LX/6aU;->A3E:Z

    .line 605
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A3C:Z

    .line 607
    iget-object v0, v2, LX/6aU;->A1F:Ljava/util/Set;

    .line 609
    iput-object v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1F:Ljava/util/Set;

    .line 611
    iget-object v0, v2, LX/6aU;->A1E:Ljava/util/Set;

    .line 613
    iput-object v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1E:Ljava/util/Set;

    .line 615
    iget-object v0, v2, LX/6aU;->A1G:Ljava/util/Set;

    .line 617
    iput-object v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1G:Ljava/util/Set;

    .line 619
    iget-boolean v0, v2, LX/6aU;->A3B:Z

    .line 621
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A39:Z

    .line 623
    iget v0, v2, LX/6aU;->A0E:I

    .line 625
    iput v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0G:I

    .line 627
    iget v0, v2, LX/6aU;->A0a:I

    .line 629
    iput v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0c:I

    .line 631
    iget v0, v2, LX/6aU;->A0C:I

    .line 633
    iput v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0F:I

    .line 635
    iget v0, v2, LX/6aU;->A01:I

    .line 637
    iput v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A04:I

    .line 639
    iget-boolean v0, v2, LX/6aU;->A2q:Z

    .line 641
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2o:Z

    .line 643
    iget-object v0, v2, LX/6aU;->A1B:Ljava/util/Set;

    .line 645
    iput-object v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1B:Ljava/util/Set;

    .line 647
    iget-boolean v0, v2, LX/6aU;->A1I:Z

    .line 649
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1e:Z

    .line 651
    iget-boolean v0, v2, LX/6aU;->A2j:Z

    .line 653
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2f:Z

    .line 655
    iget-boolean v0, v2, LX/6aU;->A1o:Z

    .line 657
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1o:Z

    .line 659
    iget-boolean v0, v2, LX/6aU;->A1c:Z

    .line 661
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1b:Z

    .line 663
    iget-boolean v0, v2, LX/6aU;->A22:Z

    .line 665
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A20:Z

    .line 667
    iget-boolean v0, v2, LX/6aU;->A25:Z

    .line 669
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A23:Z

    .line 671
    iget-object v0, v2, LX/6aU;->A10:LX/6bt;

    .line 673
    iput-object v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A10:LX/6bt;

    .line 675
    iget-boolean v0, v2, LX/6aU;->A2I:Z

    .line 677
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2H:Z

    .line 679
    iget-object v0, v2, LX/6aU;->A19:Ljava/util/Map;

    .line 681
    iput-object v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A19:Ljava/util/Map;

    .line 683
    iget-boolean v0, v2, LX/6aU;->A1W:Z

    .line 685
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1V:Z

    .line 687
    iget-boolean v0, v2, LX/6aU;->A2v:Z

    .line 689
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2t:Z

    .line 691
    iget-boolean v0, v2, LX/6aU;->A2d:Z

    .line 693
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2b:Z

    .line 695
    iget-boolean v0, v2, LX/6aU;->A37:Z

    .line 697
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A35:Z

    .line 699
    iget-boolean v0, v2, LX/6aU;->A1N:Z

    .line 701
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1M:Z

    .line 703
    iget-boolean v0, v2, LX/6aU;->A1p:Z

    .line 705
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1p:Z

    .line 707
    iget v0, v2, LX/6aU;->A05:I

    .line 709
    iput v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A08:I

    .line 711
    iget-boolean v0, v2, LX/6aU;->A1x:Z

    .line 713
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1x:Z

    .line 715
    iget v0, v2, LX/6aU;->A0I:I

    .line 717
    iput v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0K:I

    .line 719
    iget v0, v2, LX/6aU;->A04:I

    .line 721
    iput v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A07:I

    .line 723
    iget-boolean v0, v2, LX/6aU;->A3A:Z

    .line 725
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A38:Z

    .line 727
    iget-boolean v0, v2, LX/6aU;->A1j:Z

    .line 729
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1j:Z

    .line 731
    iget-boolean v0, v2, LX/6aU;->A3P:Z

    .line 733
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A3N:Z

    .line 735
    iget-object v0, v2, LX/6aU;->A1D:Ljava/util/Set;

    .line 737
    iput-object v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1D:Ljava/util/Set;

    .line 739
    iget-object v0, v2, LX/6aU;->A1C:Ljava/util/Set;

    .line 741
    iput-object v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1C:Ljava/util/Set;

    .line 743
    iget-object v0, v2, LX/6aU;->A1H:Ljava/util/Set;

    .line 745
    iput-object v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1H:Ljava/util/Set;

    .line 747
    iget-boolean v0, v2, LX/6aU;->A2O:Z

    .line 749
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2N:Z

    .line 751
    iget-boolean v0, v2, LX/6aU;->A2Z:Z

    .line 753
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2X:Z

    .line 755
    iget-boolean v0, v2, LX/6aU;->A2b:Z

    .line 757
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2Z:Z

    .line 759
    iget-boolean v0, v2, LX/6aU;->A1u:Z

    .line 761
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1u:Z

    .line 763
    iget-boolean v0, v2, LX/6aU;->A1v:Z

    .line 765
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1v:Z

    .line 767
    iget-boolean v0, v2, LX/6aU;->A1t:Z

    .line 769
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1t:Z

    .line 771
    iget v0, v2, LX/6aU;->A0O:I

    .line 773
    iput v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0Q:I

    .line 775
    iget-boolean v0, v2, LX/6aU;->A23:Z

    .line 777
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A21:Z

    .line 779
    iget-boolean v0, v2, LX/6aU;->A2N:Z

    .line 781
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2M:Z

    .line 783
    iget-boolean v0, v2, LX/6aU;->A1s:Z

    .line 785
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1s:Z

    .line 787
    iget-boolean v0, v2, LX/6aU;->A1y:Z

    .line 789
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A02:Z

    .line 791
    iget-wide v3, v2, LX/6aU;->A0e:J

    .line 793
    iput-wide v3, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A00:J

    .line 795
    iget-boolean v0, v2, LX/6aU;->A1r:Z

    .line 797
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1r:Z

    .line 799
    iget v0, v2, LX/6aU;->A08:I

    .line 801
    iput v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0B:I

    .line 803
    iget-boolean v0, v2, LX/6aU;->A20:Z

    .line 805
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1y:Z

    .line 807
    iget v0, v2, LX/6aU;->A03:I

    .line 809
    iput v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A06:I

    .line 811
    iget-boolean v0, v2, LX/6aU;->A1Y:Z

    .line 813
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1X:Z

    .line 815
    iget-boolean v0, v2, LX/6aU;->A1T:Z

    .line 817
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1S:Z

    .line 819
    iget-boolean v0, v2, LX/6aU;->A38:Z

    .line 821
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A36:Z

    .line 823
    iget-object v0, v2, LX/6aU;->A0w:LX/6aV;

    .line 825
    iput-object v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A01:LX/6aV;

    .line 827
    iget-boolean v0, v2, LX/6aU;->A1e:Z

    .line 829
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1d:Z

    .line 831
    iget-boolean v0, v2, LX/6aU;->A28:Z

    .line 833
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A26:Z

    .line 835
    iget-boolean v0, v2, LX/6aU;->A1b:Z

    .line 837
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1a:Z

    .line 839
    iget-boolean v0, v2, LX/6aU;->A2X:Z

    .line 841
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2V:Z

    .line 843
    iget-boolean v0, v2, LX/6aU;->A1i:Z

    .line 845
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1i:Z

    .line 847
    iget-boolean v0, v2, LX/6aU;->A3V:Z

    .line 849
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A3T:Z

    .line 851
    iget-boolean v0, v2, LX/6aU;->A2u:Z

    .line 853
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2s:Z

    .line 855
    iget-boolean v0, v2, LX/6aU;->A1a:Z

    .line 857
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1Z:Z

    .line 859
    iget-boolean v0, v2, LX/6aU;->A1X:Z

    .line 861
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1W:Z

    .line 863
    iget-boolean v0, v2, LX/6aU;->A21:Z

    .line 865
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1z:Z

    .line 867
    iget-boolean v0, v2, LX/6aU;->A2W:Z

    .line 869
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2G:Z

    .line 871
    iget-boolean v0, v2, LX/6aU;->A1P:Z

    .line 873
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1O:Z

    .line 875
    iget-boolean v0, v2, LX/6aU;->A2L:Z

    .line 877
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2K:Z

    .line 879
    iget-object v0, v2, LX/6aU;->A0p:LX/6bv;

    .line 881
    iput-object v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0q:LX/6bv;

    .line 883
    iget-boolean v0, v2, LX/6aU;->A1n:Z

    .line 885
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1n:Z

    .line 887
    iget-object v2, v2, LX/6aU;->A0y:LX/6bw;

    .line 889
    if-nez v2, :cond_0

    .line 891
    const/4 v3, 0x0

    .line 892
    const/16 v90, 0x0

    .line 894
    const-wide/16 v28, 0x0

    .line 896
    const-wide/16 v10, 0x0

    .line 898
    new-instance v2, LX/6bw;

    .line 900
    move-object v4, v3

    .line 901
    move-object v5, v3

    .line 902
    move-object v6, v3

    .line 903
    move-object v7, v3

    .line 904
    move-object v8, v3

    .line 905
    move-object v9, v3

    .line 906
    move-wide v12, v10

    .line 907
    move-wide v14, v10

    .line 908
    move-wide/from16 v16, v10

    .line 910
    move-wide/from16 v18, v10

    .line 912
    move-wide/from16 v20, v10

    .line 914
    move-wide/from16 v22, v10

    .line 916
    move-wide/from16 v24, v10

    .line 918
    move-wide/from16 v26, v10

    .line 920
    move-wide/from16 v30, v28

    .line 922
    move-wide/from16 v32, v28

    .line 924
    move-wide/from16 v34, v28

    .line 926
    move-wide/from16 v36, v28

    .line 928
    move-wide/from16 v38, v28

    .line 930
    move-wide/from16 v40, v28

    .line 932
    move-wide/from16 v42, v28

    .line 934
    move-wide/from16 v44, v28

    .line 936
    move-wide/from16 v46, v28

    .line 938
    move-wide/from16 v48, v28

    .line 940
    move-wide/from16 v50, v28

    .line 942
    move-wide/from16 v52, v28

    .line 944
    move-wide/from16 v54, v28

    .line 946
    move-wide/from16 v56, v28

    .line 948
    move-wide/from16 v58, v28

    .line 950
    move-wide/from16 v60, v28

    .line 952
    move-wide/from16 v62, v28

    .line 954
    move-wide/from16 v64, v28

    .line 956
    move-wide/from16 v66, v28

    .line 958
    move-wide/from16 v68, v28

    .line 960
    move-wide/from16 v70, v28

    .line 962
    move-wide/from16 v72, v28

    .line 964
    move-wide/from16 v74, v28

    .line 966
    move-wide/from16 v76, v28

    .line 968
    move-wide/from16 v78, v28

    .line 970
    move-wide/from16 v80, v28

    .line 972
    move-wide/from16 v82, v28

    .line 974
    move-wide/from16 v84, v28

    .line 976
    move-wide/from16 v86, v28

    .line 978
    move-wide/from16 v88, v28

    .line 980
    move/from16 v91, v90

    .line 982
    move/from16 v92, v90

    .line 984
    move/from16 v93, v90

    .line 986
    move/from16 v94, v90

    .line 988
    move/from16 v95, v90

    .line 990
    move/from16 v96, v90

    .line 992
    move/from16 v97, v90

    .line 994
    move/from16 v98, v90

    .line 996
    move/from16 v99, v90

    .line 998
    move/from16 v100, v90

    .line 1000
    move/from16 v101, v90

    .line 1002
    move/from16 v102, v90

    .line 1004
    move/from16 v103, v90

    .line 1006
    move/from16 v104, v90

    .line 1008
    move/from16 v105, v90

    .line 1010
    move/from16 v106, v90

    .line 1012
    move/from16 v107, v90

    .line 1014
    move/from16 v108, v90

    .line 1016
    move/from16 v109, v90

    .line 1018
    move/from16 v110, v90

    .line 1020
    move/from16 v111, v90

    .line 1022
    move/from16 v112, v90

    .line 1024
    move/from16 v113, v90

    .line 1026
    move/from16 v114, v90

    .line 1028
    move/from16 v115, v90

    .line 1030
    move/from16 v116, v90

    .line 1032
    move/from16 v117, v90

    .line 1034
    move/from16 v118, v90

    .line 1036
    move/from16 v119, v90

    .line 1038
    move/from16 v120, v90

    .line 1040
    move/from16 v121, v90

    .line 1042
    move/from16 v122, v90

    .line 1044
    move/from16 v123, v90

    .line 1046
    move/from16 v124, v90

    .line 1048
    move/from16 v125, v90

    .line 1050
    move/from16 v126, v90

    .line 1052
    move/from16 v127, v90

    .line 1054
    move/from16 v128, v90

    .line 1056
    move/from16 v129, v90

    .line 1058
    move/from16 v130, v90

    .line 1060
    move/from16 v131, v90

    .line 1062
    move/from16 v132, v90

    .line 1064
    move/from16 v133, v90

    .line 1066
    move/from16 v134, v90

    .line 1068
    move/from16 v135, v90

    .line 1070
    move/from16 v136, v90

    .line 1072
    move/from16 v137, v90

    .line 1074
    move/from16 v138, v90

    .line 1076
    move/from16 v139, v90

    .line 1078
    move/from16 v140, v90

    .line 1080
    move/from16 v141, v90

    .line 1082
    move/from16 v142, v90

    .line 1084
    move/from16 v143, v90

    .line 1086
    move/from16 v144, v90

    .line 1088
    move/from16 v145, v90

    .line 1090
    move/from16 v146, v90

    .line 1092
    move/from16 v147, v90

    .line 1094
    move/from16 v148, v90

    .line 1096
    move/from16 v149, v90

    .line 1098
    move/from16 v150, v90

    .line 1100
    move/from16 v151, v90

    .line 1102
    move/from16 v152, v90

    .line 1104
    move/from16 v153, v90

    .line 1106
    move/from16 v154, v90

    .line 1108
    move/from16 v155, v90

    .line 1110
    move/from16 v156, v90

    .line 1112
    move/from16 v157, v90

    .line 1114
    move/from16 v158, v90

    .line 1116
    move/from16 v159, v90

    .line 1118
    move/from16 v160, v90

    .line 1120
    move/from16 v161, v90

    .line 1122
    move/from16 v162, v90

    .line 1124
    move/from16 v163, v90

    .line 1126
    move/from16 v164, v90

    .line 1128
    move/from16 v165, v90

    .line 1130
    move/from16 v166, v90

    .line 1132
    move/from16 v167, v90

    .line 1134
    move/from16 v168, v90

    .line 1136
    move/from16 v169, v90

    .line 1138
    move/from16 v170, v90

    .line 1140
    move/from16 v171, v90

    .line 1142
    move/from16 v172, v90

    .line 1144
    move/from16 v173, v90

    .line 1146
    move/from16 v174, v90

    .line 1148
    move/from16 v175, v90

    .line 1150
    move/from16 v176, v90

    .line 1152
    move/from16 v177, v90

    .line 1154
    move/from16 v178, v90

    .line 1156
    move/from16 v179, v90

    .line 1158
    move/from16 v180, v90

    .line 1160
    move/from16 v181, v90

    .line 1162
    move/from16 v182, v90

    .line 1164
    move/from16 v183, v90

    .line 1166
    move/from16 v184, v90

    .line 1168
    move/from16 v185, v90

    .line 1170
    move/from16 v186, v90

    .line 1172
    move/from16 v187, v90

    .line 1174
    move/from16 v188, v90

    .line 1176
    move/from16 v189, v90

    .line 1178
    move/from16 v190, v90

    .line 1180
    move/from16 v191, v90

    .line 1182
    move/from16 v192, v90

    .line 1184
    move/from16 v193, v90

    .line 1186
    move/from16 v194, v90

    .line 1188
    move/from16 v195, v90

    .line 1190
    move/from16 v196, v90

    .line 1192
    move/from16 v197, v90

    .line 1194
    move/from16 v198, v90

    .line 1196
    move/from16 v199, v90

    .line 1198
    move/from16 v200, v90

    .line 1200
    move/from16 v201, v90

    .line 1202
    move/from16 v202, v90

    .line 1204
    move/from16 v203, v90

    .line 1206
    move/from16 v204, v90

    .line 1208
    move/from16 v205, v90

    .line 1210
    move/from16 v206, v90

    .line 1212
    move/from16 v207, v90

    .line 1214
    move/from16 v208, v90

    .line 1216
    move/from16 v209, v90

    .line 1218
    move/from16 v210, v90

    .line 1220
    move/from16 v211, v90

    .line 1222
    move/from16 v212, v90

    .line 1224
    move/from16 v213, v90

    .line 1226
    move/from16 v214, v90

    .line 1228
    move/from16 v215, v90

    .line 1230
    move/from16 v216, v90

    .line 1232
    move/from16 v217, v90

    .line 1234
    move/from16 v218, v90

    .line 1236
    move/from16 v219, v90

    .line 1238
    move/from16 v220, v90

    .line 1240
    move/from16 v221, v90

    .line 1242
    move/from16 v222, v90

    .line 1244
    move/from16 v223, v90

    .line 1246
    move/from16 v224, v90

    .line 1248
    move/from16 v225, v90

    .line 1250
    move/from16 v226, v90

    .line 1252
    move/from16 v227, v90

    .line 1254
    move/from16 v228, v90

    .line 1256
    move/from16 v229, v90

    .line 1258
    move/from16 v230, v90

    .line 1260
    move/from16 v231, v90

    .line 1262
    move/from16 v232, v90

    .line 1264
    move/from16 v233, v90

    .line 1266
    move/from16 v234, v90

    .line 1268
    move/from16 v235, v90

    .line 1270
    move/from16 v236, v90

    .line 1272
    move/from16 v237, v90

    .line 1274
    move/from16 v238, v90

    .line 1276
    move/from16 v239, v90

    .line 1278
    move/from16 v240, v90

    .line 1280
    move/from16 v241, v90

    .line 1282
    move/from16 v242, v90

    .line 1284
    move/from16 v243, v90

    .line 1286
    move/from16 v244, v90

    .line 1288
    move/from16 v245, v90

    .line 1290
    move/from16 v246, v90

    .line 1292
    move/from16 v247, v90

    .line 1294
    move/from16 v248, v90

    .line 1296
    move/from16 v249, v90

    .line 1298
    move/from16 v250, v90

    .line 1300
    move/from16 v251, v90

    .line 1302
    move/from16 v252, v90

    .line 1304
    move/from16 v253, v90

    .line 1306
    move/from16 v254, v90

    .line 1308
    move/from16 v255, v90

    .line 1310
    invoke-direct/range {v2 .. v255}, LX/6bw;-><init>(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;DDDDDDDDDJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ)V

    .line 1313
    :cond_0
    iput-object v2, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0y:LX/6bw;

    .line 1315
    return-void
.end method
